name: Deploy web app

env:
  AZURE_WEBAPP_NAME: 'yeh-simple-abp'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  
on:
  workflow_dispatch:
    
jobs:
  call_build_job:
    uses: './.github/workflows/build-and-test.yml'
  deploy:
    runs-on: ubuntu-latest
    needs: call_build_job
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  