name: Build and test asp.net core web app

on:
  workflow_call:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: dotnet publish
        run: dotnet publish MyMinimalApi\MyMinimalApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp