name: Publish asp.net core web app

on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  call_build_job:
    uses: './.github/workflows/build-and-test.yml'
  publish:
    runs-on: ubuntu-latest
    needs: call_build_job
    steps:
      - name: dotnet publish
        run: dotnet publish ./MyMinimalApi/MyMinimalApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
